node {
    def project
    def image
    
    docker.withRegistry('http://localhost:5000') {
        stage('Prepare') {
            checkout scm
            project = readYaml file: './.ci/project.yml'
        }
        stage('Build') {
            image = docker.build("${project.name}:${project.version}", "-f ./.ci/Dockerfile .")
        }
        stage('Push') {
            image.push()
        }
    }
}
