node {
    def project
    def image
    
    docker.withRegistry('http://localhost:5000') {
        stage('Prepare') {
            checkout scm
            project = readYaml file: './.ci/project.yml'
        }
        stage('Build') {
            image = docker.build("${project.name}:${project.version}", "-f ./.ci/Dockerfile .")
        }
        stage('Push') {
            image.push()
        }
        stage('Deploy') {
            withCredentials([string(credentialsId: 'cashfazz-deployer-staging', variable: 'token')]) {
                sh "curl -fsSH 'Content-Type: application/json' -d '{\"name\":\"${project.name}\",\"ver\":\"${project.version}\",\"token\":\"${token}\"}' http://10.13.0.131/deploy"
            }
        }
    }
}
